// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MyApp",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MyApp",
            targets: ["MyApp"],
            bundleIdentifier: "ios.github.leonardolu.swiftpmWWDC",
            teamIdentifier: "ZZM746LVXC",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeLeft,
                .landscapeRight,
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "MyApp",
            path: "App"
        )
    ]
)